In [1]:
import pandas as pd
from pathlib import Path

In [2]:
path = '../data/processed/splits/train.parquet'

In [3]:
train = pd.read_parquet(path)

In [4]:
train.head()

   user_id  movie_id  rating  timestamp  user_idx  item_idx  pos  len
0        1      3186       4  978300019         0      2969    0   53
1        1      1270       5  978300055         0      1178    1   53
2        1      1721       4  978300055         0      1574    2   53
3        1      1022       5  978300055         0       957    3   53
4        1      2340       3  978300103         0      2147    4   53

In [5]:
train.shape

(988129, 8)

In [6]:
train.tail(10)

        user_id  movie_id  rating  timestamp  user_idx  item_idx  pos  len
988119     6040      1333       4  997454140      6039      1236  329  341
988120     6040       953       5  997454160      6039       892  330  341
988121     6040      2725       4  997454180      6039      2520  331  341
988122     6040      1673       4  997454212      6039      1536  332  341
988123     6040       457       4  997454349      6039       443  333  341
988124     6040      3671       4  997454367      6039      3429  334  341
988125     6040       232       5  997454398      6039       225  335  341
988126     6040      2917       4  997454429      6039      2709  336  341
988127     6040      1921       4  997454464      6039      1741  337  341
988128     6040      1784       3  997454464      6039      1618  338  341

In [7]:
train['item_next'] = train['item_idx'].shift(-1)
train['user_next'] = train['user_id'].shift(-1)

In [8]:
train.head()

,user_id,movie_id,rating,timestamp,user_idx,item_idx,pos,len,item_next,user_next
0,1,3186,4,978300019,0,2969,0,53,1178.0,1.0
1,1,1270,5,978300055,0,1178,1,53,1574.0,1.0
2,1,1721,4,978300055,0,1574,2,53,957.0,1.0
3,1,1022,5,978300055,0,957,3,53,2147.0,1.0
4,1,2340,3,978300103,0,2147,4,53,1658.0,1.0

In [9]:
train.tail()

,user_id,movie_id,rating,timestamp,user_idx,item_idx,pos,len,item_next,user_next
988124,6040,3671,4,997454367,6039,3429,334,341,225.0,6040.0
988125,6040,232,5,997454398,6039,225,335,341,2709.0,6040.0
988126,6040,2917,4,997454429,6039,2709,336,341,1741.0,6040.0
988127,6040,1921,4,997454464,6039,1741,337,341,1618.0,6040.0
988128,6040,1784,3,997454464,6039,1618,338,341,NaN,NaN

In [16]:
pairs = train[(train['user_id'] == train['user_next']) & (train['item_next'].notna())]

In [17]:
pairs.head()

,user_id,movie_id,rating,timestamp,user_idx,item_idx,pos,len,item_next,user_next
0,1,3186,4,978300019,0,2969,0,53,1178.0,1.0
1,1,1270,5,978300055,0,1178,1,53,1574.0,1.0
2,1,1721,4,978300055,0,1574,2,53,957.0,1.0
3,1,1022,5,978300055,0,957,3,53,2147.0,1.0
4,1,2340,3,978300103,0,2147,4,53,1658.0,1.0

In [18]:
pairs[['item_next', 'user_next']] = pairs[['item_next', 'user_next']].astype(int)

C:\Users\User\AppData\Local\Temp\ipykernel_16840\3090385949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pairs[['item_next', 'user_next']] = pairs[['item_next', 'user_next']].astype(int)

In [19]:
pairs

,user_id,movie_id,rating,timestamp,user_idx,item_idx,pos,len,item_next,user_next
0,1,3186,4,978300019,0,2969,0,53,1178,1
1,1,1270,5,978300055,0,1178,1,53,1574,1
2,1,1721,4,978300055,0,1574,2,53,957,1
3,1,1022,5,978300055,0,957,3,53,2147,1
4,1,2340,3,978300103,0,2147,4,53,1658,1
...,...,...,...,...,...,...,...,...,...,...
988123,6040,457,4,997454349,6039,443,333,341,3429,6040
988124,6040,3671,4,997454367,6039,3429,334,341,225,6040
988125,6040,232,5,997454398,6039,225,335,341,2709,6040
988126,6040,2917,4,997454429,6039,2709,336,341,1741,6040
988127,6040,1921,4,997454464,6039,1741,337,341,1618,6040

In [23]:
co_pairs = pairs[['item_idx', 'item_next']]

In [24]:
co_pairs.head()

   item_idx  item_next
0      2969       1178
1      1178       1574
2      1574        957
3       957       2147
4      2147       1658

In [25]:
co_pairs.shape

(982089, 2)

In [26]:
OUT_DIR = Path("../data/processed/sid_pairs")
OUT_DIR.mkdir(parents=False, exist_ok=True)

In [27]:
out_path = OUT_DIR / "co_pairs_neighbors.parquet"

In [28]:
co_pairs.to_parquet(out_path, index=False)